name: Invoice b Database

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Choose the task to run'
        required: true
        default: 'migrate'
        type: choice
        options:
          - migrate
          - rollback_migrate
          - seed
          - rollback_seed

jobs:
  setup:
    name: Setup Staging Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Set up Staging Environment Variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "NODE_ENV=staging" >> .env
          
          echo "cat .env"
          cat .env

  rollback_migrate:
    name: Rollback Migration in Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.task == 'rollback_migrate' }}
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Rollback Migration in Staging
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            cd ~/fin-invoice-ocr-team6/backend &&
            npx sequelize-cli db:migrate:undo --env ${{ github.event.inputs.environment }}
          "

  migrate:
    name: Run Migrations in Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.task == 'migrate' }}
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Run Migrations in Staging
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            cd ~/fin-invoice-ocr-team6/backend &&
            npx sequelize-cli db:migrate --env ${{ github.event.inputs.environment }}
          "

  rollback_seed:
    name: Rollback Seeders in Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.task == 'rollback_seed' }}
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Rollback Seeders in Staging
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            cd ~/fin-invoice-ocr-team6/backend &&
            npx sequelize-cli db:seed:undo --seed 20250226143621-seed-invoice.js --env ${{ github.event.inputs.environment }}
          "

  seed:
    name: Seed Data in Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.task == 'seed' }}
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Rerun Seeder in Staging
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            cd ~/fin-invoice-ocr-team6/backend &&
            npx sequelize-cli db:seed --seed 20250226143621-seed-invoice.js --env ${{ github.event.inputs.environment }}
          "
