name: Manual Trigger CI/CD Workflow

on:
  workflow_dispatch:  # Manual trigger for the workflow

jobs:
  rollback:
    name: Rollback Migration in Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Rollback Migration in Staging
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            cd ~/fin-invoice-ocr-team6/backend &&
            npx sequelize-cli db:migrate:undo --env staging
          "

  migrate:
    name: Run Migrations in Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Run Migrations in Staging
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            cd ~/fin-invoice-ocr-team6/backend &&
            npx sequelize-cli db:migrate --env staging
          "

  seed:
    name: Seed Data in Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: sudo apt-get install openssh-client

      - name: Create SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ssh-key.pem

      - name: Update SSH Key Permissions
        run: chmod 400 ssh-key.pem

      - name: Rerun Seeder in Staging
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
            cd ~/fin-invoice-ocr-team6/backend &&
            npx sequelize-cli db:seed:all --env staging
          "
